// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7biknLOn0Od1NR-8v75pVvgVY_5zoBU',
    appId: '1:485344786107:web:ecdae6201d75241e3d9b9e',
    databaseURL: 'https://fir-2af6b-default-rtdb.firebaseio.com/',
    messagingSenderId: '485344786107',
    projectId: 'fir-2af6b',
    authDomain: 'fir-2af6b.firebaseapp.com',
    storageBucket: 'fir-2af6b.appspot.com',
    measurementId: 'G-ENETBVCWQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVho6ZAzm2XXmTVXufkml6jDpFyuRrqPc',
    appId: '1:485344786107:android:30ca69c572b830903d9b9e',
    messagingSenderId: '485344786107',
    projectId: 'fir-2af6b',
    storageBucket: 'fir-2af6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPe4YR--qxuXLjL3v_TKKAeg5-uP8vjVc',
    appId: '1:485344786107:ios:145a107a053bdbaf3d9b9e',
    messagingSenderId: '485344786107',
    projectId: 'fir-2af6b',
    storageBucket: 'fir-2af6b.appspot.com',
    iosClientId:
        '485344786107-8pf14gcvgj43jskjrcn873edg9uu28gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPe4YR--qxuXLjL3v_TKKAeg5-uP8vjVc',
    appId: '1:485344786107:ios:145a107a053bdbaf3d9b9e',
    messagingSenderId: '485344786107',
    projectId: 'fir-2af6b',
    storageBucket: 'fir-2af6b.appspot.com',
    iosClientId:
        '485344786107-8pf14gcvgj43jskjrcn873edg9uu28gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
